GET http://localhost:3000/shoes

###

GET http://localhost:3000/shoes/2

###

POST http://localhost:3000/shoes
Content-Type: application/json

{
  "brand": "Nike",
  "color": "White",
  "model": "Air Force 1's",
  "style": "Gym Shoes"

}

###

PATCH http://localhost:3000/shoes/1
Content-Type: application/json

{
  "model": "Air Maximus"
}

###
DELETE http://localhost:3000/shoes/2